# =====================================================================================
# LING48/CS72 Homework 1: Eliza-style Chatbot
# Rolando Coto (rolando.a.coto.solano@dartmouth.edu)
# Last modification: 2023/03/28
#
# The program uses regular expressions to parse a user's input and generate a
# response in English. Be sure to test your regular expressions. I recommend
# making them in a site like https://regex101.com/. 
# =====================================================================================

# Import libraries for processing of operating system input (os,sys), 
# string handling (string) and regular expressions (re)
import os
import string
import sys
import re


# =====================================================================================
# Function:     eliza
#
# Input:        userInput (a string with a phrase in the English language)
# Output:       reply (a string with a response, in English, generated by the function)
# Description:  The function uses regular expressions to read input from the user
#               and produce a response using natural language (English). Right now the
#               function is just a template, so it can only respond to the question
#               "What is your name?".
# =====================================================================================

def eliza(userInput):

    # Create the variable output, which will contain our response
    output = ""

    # Create the regular expressions
    # You can test your regular expressions in numerous websites, such as https://regex101.com/
    reHello1 = r"I'm (.*)"
    reHello2 = r"[Mm]y name is (.*)"
    reHello3 = r"I am (.*)"

    groupHello1 = re.search(reHello1,userInput,re.IGNORECASE)
    groupHello2 = re.search(reHello2,userInput,re.IGNORECASE)
    groupHello3 = re.search(reHello3,userInput,re.IGNORECASE)

    # if the input matches the regular expression:
    #if (re.compile(reHello1).match(input)):
    if (groupHello1 != None):
        # Then search for the first capturing group and extract it.
        # Then, use it to construct the string "Hello, CAPTUREGROUP1!"
        # and put it in the output variable.
        output = "Hi, " + groupHello1.group(1) + ". How are you?"
    # If the input doesn't match the first regular expression, then
    # keep trying to match it to the other regular expressions we have.
    elif (groupHello2 != None):
        output = "Hi, " + groupHello2.group(1) + ". How are you?"
    elif (groupHello3 != None):
        output = "Hi, " + groupHello3.group(1) + ". How are you?"
    # If the input does not match any of the regular expressions,
    # then say that you didn't understand what the user wrote.
    else:
        output = "I didn't understand you"
        
    return output


# =====================================================================================
# Main body of the program
# The system listens to the input argument from the
# command line and generates a response in English.
# =====================================================================================


# Read the input from the command line.
# If there are fewer than 2 arguments (the python file name and the input phrase),
# then the program will tell you that there was an error.
if (len(sys.argv) < 2):
    input = ""
    print("\nERROR: You didn't provide an input phrase\n")
else:
    input  = os.path.join("",sys.argv[1])
    output = eliza(input)
    # Print the input and the output
    print("You:      " + input)
    print("Computer: " + output)